### ISSUE TITLE
feature request: dockerimage for easier testing 

### ISSUE THREAD

**Issue by skeptrunedev** [lanterndata/lantern#152]
TLDR, we @arguflow would like to test this out asap to see how it compares to pgvector v0.5.0 but would like to avoid building from source if at all possible. 

It should be an extremely quick test considering we have a notebook already working for pgvector - https://github.com/arguflow/pgvector-vs-qdrant-comparison/blob/main/qdrant-to-pgvector.ipynb .

**Comment by skeptrunedev** [comment]
Nevermind, found it.

**Comment by jeungsp** [comment]
Excellent, curious to hear the results.

Would you mind sharing feedback / outcome to support@lantern.dev?

Also, if there's ANYTHING we can do to help your use case, please let us know!

**Comment by skeptrunedev** [comment]
> Excellent, curious to hear the results.
> 
> Would you mind sharing feedback / outcome to [support@lantern.dev](mailto:support@lantern.dev)?
> 
> Also, if there's ANYTHING we can do to help your use case, please let us know!

Hopped in discord, want to talk more there? There are quite a few things which would help us out.
