### ISSUE TITLE
Add script to upgrade the DB from v0.0.X to v0.0.Y and run all the tests

### ISSUE THREAD

**Issue by Ngalstyan4** [lanterndata/lantern#178]
Once the script is ready, we can add it to ci/cd to run for all supported minor version upgrades and ensure that upgrade scripts work properly

**Comment by PratikDevlekar** [comment]
Hey @Ngalstyan4 ,

I’m willing to work on this thread, Please let me know if you have made any progress regarding this issue.

There are two approaches for addressing the upgrade. The first involves creating a manual upgrading script, while the second entails utilizing the `pg_upgrade` utility. Personally, I believe that using the utility is a more efficient option to pursue.

**Comment by Ngalstyan4** [comment]
Hi @PratikDevlekar,
Thanks for expressing interest!

`pg_upgrade` is for upgrading from one major version of postgres to another [^1]. This issue is about extension upgrades (minor and major) and not postgres major version upgrades[^2]. Hope this clarifies the issue.

[^1]: https://www.postgresql.org/docs/current/pgupgrade.html
[^2]: https://www.postgresql.org/docs/current/sql-alterextension.html
