### ISSUE TITLE
current main(fbf0d1704e1ec) build failure on Debian

### ISSUE THREAD

**Issue by broccoliSpicy** [lanterndata/lantern#301]
<img width="991" alt="Screenshot 2024-03-27 at 12 16 46 PM" src="https://github.com/lanterndata/lantern/assets/93440049/10a2f9c9-82d7-45ed-85ec-6b676f839734">

**Comment by broccoliSpicy** [comment]
[issue#59](https://github.com/lanterndata/lantern/issues/59)
[userach issue](https://github.com/unum-cloud/usearch/issues/202)

we didn't thoroughly solve this issue, 

we recently enabled -march=native,  #299 , which makes this problem manifest again

**Comment by Ngalstyan4** [comment]
@broccoliSpicy , thanks for pointing this out.
This is a compiler issue. `_Float16` is not available prior to gcc/g++ 12. So, to build with `-march=native`, make sure you have gcc-12, g++-12 or newer

Installation prerequisites: https://lantern.dev/docs/lantern-db/install

**Comment by broccoliSpicy** [comment]
Sorry I overlooked the installation prerequisites
my gcc version was 10.2.1.

updated gcc to 13 and indeed the build succeed.
