### ISSUE TITLE
Docker setup doesn't work

### ISSUE THREAD

**Issue by sdan** [lanterndata/lantern#307]
`docker run --pull=always --rm -p 5432:5432 -e "POSTGRES_USER=$USER" -e "POSTGRES_PASSWORD=postgres" -v ./lantern_data:/var/lib/postgresql/data lanterndata/lantern:latest-pg15`

docker: Error response from daemon: create ./lantern_data: "./lantern_data" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.

**Comment by Ngalstyan4** [comment]
Hi @sdan , could you share some details about your platform and environment? I just tried this on an ubuntu 22.04 and Debian 11 and macOS Venture 13.0 (all x86-64 arch). It worked on all 3.

**Comment by sdan** [comment]
macOS 14.1 the example in the readme just doesn't have the relative path
