### ISSUE TITLE
Typo in Comments: Correct 'enought' to 'enough' in scan.c

### ISSUE THREAD

**Issue by hydrationn** [lanterndata/lantern#353]
Hello,

I found a typo in the lantern_hnsw/src/hnsw/scan.c file on line 311, where the word "enought" is mistakenly used instead of "enough" in the comment. Correcting this minor typo would improve readability and maintenance of the code.

Could I please have permission to commit this fix? Thank you very much for considering this request!

**Comment by var77** [comment]
Hi @hydrationn, thanks for noticing the issue. You can fork the repository commit the required changes on you fork and open PR to the upstream repo.
